name: "Test"
on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  test:
    if: github.event.pull_request.merged == true
    name: "test"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - name: "Merge Main into feature branch"
        run: |

          git config --global user.email "ci@example.com"
          git config --global user.name "CI"

          git checkout $GITHUB_BASE_REF
          git pull
          git checkout $GITHUB_HEAD_REF
          git merge $GITHUB_BASE_REF --allow-unrelated-histories
          git push
