name: "Test"
on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  test:
    if: github.event.pull_request.merged == true
    name: "test"
    runs-on: ubuntu-latest
    steps:
      - name: "Check Env Vars"
        run: |
          echo $GITHUB_REF_NAME
          echo $GITHUB_REF
          echo $GITHUB_BASE_REF
