name: "Test"
on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write

jobs:
  test:
    if: github.event.pull_request.merged == true
    name: "test"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - run: |
          echo "branch_name=$GITHUB_HEAD_REF" >> "$GITHUB_OUTPUT"
        id: branch_name
      - name: Merge main to environment branch
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: ${{ steps.branch_name.outputs.branch_name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: Merge to ${{ steps.branch_name.outputs.branch_name }} from main/master
