name: "Test"
on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write

jobs:
  test:
    if: github.event.pull_request.merged == true
    name: "test"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - name: Merge main to environment branch
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: $GITHUB_HEAD_REF
          github_token: ${{ secrets.GITHUB_TOKEN }}
